<?php

namespace IntentRestAPI\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends EntityRepository
{
}
