<?php

namespace IntentRestAPI\UserBundle\Entity\Repositories\MainUserRepository;

use Doctrine\ORM\EntityRepository;

/**
 * MainUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainUserRepository extends EntityRepository
{
}
