<?php

namespace IntentRestAPI\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserResaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserResaRepository extends EntityRepository
{
}
