<?php

namespace IntentRestAPI\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCommandeRepository extends EntityRepository
{
}
