<?php

namespace IntentRestAPI\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    /**
     * Renvoi tout les produits actif de la base.
     * @return <Array> $oProduits
     */
    public function getAllActifProduct() {
        $aProduits = $this->createQueryBuilder('p')
            ->where("p.actif = 1")
            ->getQuery()->getResult();
        return $aProduits;
    }
}
