<?php

namespace IntentRestAPI\PizzaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaladeRepository extends EntityRepository
{
}
